name: Build and Push Docker Image (baseurl-it-tools)

env:
  VITE_VERCEL_ENV: production

on:
  push:
    branches:
      - chore/all-my-stuffs

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Run linters
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build the app
        run: pnpm build

  build:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: sharevb/it-tools
          labels: |
            org.opencontainers.image.version=baseurl-it-tools

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push (BASE_URL)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "BASE_URL=/it-tools/"
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            sharevb/it-tools:baseurl-it-tools
            ghcr.io/sharevb/it-tools:baseurl-it-tools

      # Optionally log out
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io